---
- name: 'Set undefined values to their defaults'
  ansible.builtin.set_fact:
    _vhost: "{{ nginx_vhost_defaults | ansible.builtin.combine(vhost) }}"

- name: 'Install per-vhost configuration files'
  ansible.builtin.template:
    dest: "{{ nginx_config_dir['nginx'] }}sites-available/{{ _vhost.filename }}"
    src: "{{ _vhost.template | default('vhost.conf.j2') }}"
    owner: root
    group: root
    mode: '0644'
  notify: 'Reload nginx'

- name: 'Enable per-vhost configuration files'
  ansible.builtin.file:
    state: link
    src: "{{ nginx_config_dir['nginx'] }}sites-available/{{ _vhost.filename }}"
    dest: "{{ nginx_config_dir['nginx'] }}sites-enabled/{{ _vhost.filename }}"
  notify: 'Reload nginx'
