---
- name: 'Set undefined values to their defaults'
  set_fact:
    _vhost: "{{ nginx_vhost_defaults | combine(vhost) }}"

- name: 'Install per-vhost configuration files'
  template:
    dest: "{{ nginx_config_dir['nginx'] }}sites-available/{{ _vhost.filename }}"
    src: "{{ _vhost.template | default('vhost.conf.j2') }}"
    owner: root
    group: root
    mode: 0644
  notify: 'Reload nginx'

- name: 'Enable per-vhost configuration files'
  file:
    state: link
    src: "{{ nginx_config_dir['nginx'] }}sites-available/{{ _vhost.filename }}"
    dest: "{{ nginx_config_dir['nginx'] }}sites-enabled/{{ _vhost.filename }}"
  notify: 'Reload nginx'
