---
- name: 'Restart nginx'
  service:
    name: "{{ nginx_service_name['nginx'] }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'restarted') }}"

- name: 'Reload nginx'
  service:
    name: "{{ nginx_service_name['nginx'] }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'reloaded') }}"

- name: 'Restart php-fpm'
  service:
    name: "{{ nginx_service_name['php'] }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'restarted') }}"
  when: "_use_php"

- name: 'Reload php-fpm'
  service:
    name: "{{ nginx_service_name['php'] }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'reloaded') }}"
  when: "_use_php"

- name: 'Update nginx compressed static files'
  command: '/usr/local/sbin/update_gzip_static.sh'
  listen: 'nginx_update_gzip_static'
  when: "nginx_gzip_static | bool"
